/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zadatakhibernate;

import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author wedad
 */
public class Glavni extends javax.swing.JFrame {

    /**
     * Creates new form Glavni
     */
    Person p;

    public Session session = NewHibernateUtil.getSessionFactory().openSession();
    public Transaction tx = null;

    public Glavni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unos = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        godine = new javax.swing.JTextField();
        ime = new javax.swing.JTextField();
        dohodak = new javax.swing.JTextField();
        adresa = new javax.swing.JTextField();
        unesi = new javax.swing.JToggleButton();
        unesi1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        brisanje = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        br = new javax.swing.JTextArea();
        jToggleButton10 = new javax.swing.JToggleButton();
        izmjena = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pr = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        izm = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ime1 = new javax.swing.JRadioButton();
        godine1 = new javax.swing.JRadioButton();
        adresa1 = new javax.swing.JRadioButton();
        dohodak1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ime2 = new javax.swing.JTextField();
        adresa2 = new javax.swing.JTextField();
        doho2 = new javax.swing.JTextField();
        godine2 = new javax.swing.JTextField();
        jToggleButton7 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        svi = new javax.swing.JFrame();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sviz = new javax.swing.JTextArea();
        jToggleButton8 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pretraga = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        im = new javax.swing.JRadioButton();
        godin = new javax.swing.JRadioButton();
        adr = new javax.swing.JRadioButton();
        doh = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        i = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        dohoh = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        prik = new javax.swing.JTextArea();
        action = new javax.swing.JToggleButton();
        action1 = new javax.swing.JToggleButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField10 = new javax.swing.JTextField();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        unos.setBounds(new java.awt.Rectangle(500, 300, 600, 400));

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Novi Uposlenik");

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Ime :");

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Godine :");

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Adresa :");

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Visina Dohotka :");

        godine.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        ime.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        dohodak.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        adresa.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        unesi.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        unesi.setForeground(new java.awt.Color(0, 51, 255));
        unesi.setText("Unesi");
        unesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unesiActionPerformed(evt);
            }
        });

        unesi1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        unesi1.setForeground(new java.awt.Color(0, 51, 255));
        unesi1.setText("Izbrisi");
        unesi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unesi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unosLayout = new javax.swing.GroupLayout(unos.getContentPane());
        unos.getContentPane().setLayout(unosLayout);
        unosLayout.setHorizontalGroup(
            unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(unosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(unesi))
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(unosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(godine, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dohodak, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(unosLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(unesi1)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        unosLayout.setVerticalGroup(
            unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(godine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dohodak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unesi1)
                    .addComponent(unesi))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        brisanje.setBounds(new java.awt.Rectangle(600, 300, 900, 600));

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Brisanje Uposlenih");

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("ID Uposlenog :");

        d.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        jToggleButton5.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(0, 0, 255));
        jToggleButton5.setText("Izbrisi ");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(0, 0, 255));
        jToggleButton6.setText("Izbrisi text");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        br.setBackground(new java.awt.Color(153, 153, 255));
        br.setColumns(20);
        br.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        br.setRows(5);
        jScrollPane7.setViewportView(br);

        jToggleButton10.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton10.setForeground(new java.awt.Color(0, 0, 255));
        jToggleButton10.setText("Prikaz svih");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout brisanjeLayout = new javax.swing.GroupLayout(brisanje.getContentPane());
        brisanje.getContentPane().setLayout(brisanjeLayout);
        brisanjeLayout.setHorizontalGroup(
            brisanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brisanjeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(brisanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brisanjeLayout.createSequentialGroup()
                        .addGroup(brisanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(brisanjeLayout.createSequentialGroup()
                                .addComponent(jToggleButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton6))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(brisanjeLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton5)
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brisanjeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(330, 330, 330))
        );
        brisanjeLayout.setVerticalGroup(
            brisanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brisanjeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(48, 48, 48)
                .addGroup(brisanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(brisanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton6))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        izmjena.setBounds(new java.awt.Rectangle(700, 200, 900, 700));

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Izmjena podataka o zaposlenim na osnovi ID");

        pr.setBackground(new java.awt.Color(153, 153, 255));
        pr.setColumns(20);
        pr.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        pr.setRows(5);
        jScrollPane1.setViewportView(pr);

        jLabel12.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("(Uposlenik kojeg treba izmjeniti)");

        jLabel13.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Pretraga po ID :");

        izm.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Sta zelite izmjeniti :");

        ime1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        ime1.setForeground(new java.awt.Color(0, 0, 255));
        ime1.setText("Ime");
        ime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ime1ActionPerformed(evt);
            }
        });

        godine1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        godine1.setForeground(new java.awt.Color(0, 0, 255));
        godine1.setText("Godine");
        godine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godine1ActionPerformed(evt);
            }
        });

        adresa1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        adresa1.setForeground(new java.awt.Color(0, 0, 255));
        adresa1.setText("Adresa");
        adresa1.setToolTipText("");
        adresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresa1ActionPerformed(evt);
            }
        });

        dohodak1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        dohodak1.setForeground(new java.awt.Color(0, 0, 255));
        dohodak1.setText("Dohodak");
        dohodak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dohodak1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Novo ime :");

        jLabel17.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Nova adresa :");

        jLabel18.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Novi dohodak :");

        jLabel19.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Promjeni godine :");

        ime2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        adresa2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        doho2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        godine2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        jToggleButton7.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton7.setForeground(new java.awt.Color(0, 0, 255));
        jToggleButton7.setSelected(true);
        jToggleButton7.setText("Promjeni");
        jToggleButton7.setActionCommand("");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Pretraga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton9.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton9.setForeground(new java.awt.Color(0, 0, 255));
        jToggleButton9.setSelected(true);
        jToggleButton9.setText("Obrisi text");
        jToggleButton9.setActionCommand("");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout izmjenaLayout = new javax.swing.GroupLayout(izmjena.getContentPane());
        izmjena.getContentPane().setLayout(izmjenaLayout);
        izmjenaLayout.setHorizontalGroup(
            izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izmjenaLayout.createSequentialGroup()
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel11))
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(izmjenaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(izm, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(izmjenaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(38, 38, 38)
                                .addComponent(ime1)
                                .addGap(57, 57, 57)
                                .addComponent(godine1)
                                .addGap(29, 29, 29)
                                .addComponent(adresa1)
                                .addGap(53, 53, 53)
                                .addComponent(dohodak1))))
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(izmjenaLayout.createSequentialGroup()
                                .addComponent(jToggleButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton9))
                            .addGroup(izmjenaLayout.createSequentialGroup()
                                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ime2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(izmjenaLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(doho2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(izmjenaLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(godine2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(5588, Short.MAX_VALUE))
        );
        izmjenaLayout.setVerticalGroup(
            izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izmjenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(23, 23, 23)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(izm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ime1)
                    .addComponent(godine1)
                    .addComponent(adresa1)
                    .addComponent(dohodak1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(doho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(adresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(godine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton9))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTextField3.setText("jTextField3");

        jLabel15.setText("jLabel15");

        svi.setBounds(new java.awt.Rectangle(600, 200, 1000, 700));

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Prikaz svih zaposlenih");

        sviz.setBackground(new java.awt.Color(153, 153, 255));
        sviz.setColumns(20);
        sviz.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        sviz.setRows(5);
        jScrollPane3.setViewportView(sviz);

        jToggleButton8.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton8.setForeground(new java.awt.Color(51, 51, 255));
        jToggleButton8.setText("Pretraga");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sviLayout = new javax.swing.GroupLayout(svi.getContentPane());
        svi.getContentPane().setLayout(sviLayout);
        sviLayout.setHorizontalGroup(
            sviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sviLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sviLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(sviLayout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jToggleButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sviLayout.setVerticalGroup(
            sviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sviLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel20)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jToggleButton8)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        pretraga.setBounds(new java.awt.Rectangle(700, 200, 850, 700));

        jLabel21.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Pretraga zaposlenih na osnovu ID");

        im.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        im.setForeground(new java.awt.Color(0, 51, 255));
        im.setText("Ime");
        im.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imActionPerformed(evt);
            }
        });

        godin.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        godin.setForeground(new java.awt.Color(0, 51, 255));
        godin.setText("Godine");
        godin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godinActionPerformed(evt);
            }
        });

        adr.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        adr.setForeground(new java.awt.Color(0, 51, 255));
        adr.setText("Adresa");
        adr.setToolTipText("");
        adr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrActionPerformed(evt);
            }
        });

        doh.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        doh.setForeground(new java.awt.Color(0, 51, 255));
        doh.setText("Dohodak");
        doh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dohActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Ime :");

        i.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("Godine :");

        g.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("Adresu :");

        add.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Dohodak :");

        dohoh.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N

        prik.setBackground(new java.awt.Color(153, 153, 255));
        prik.setColumns(20);
        prik.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        prik.setRows(5);
        jScrollPane6.setViewportView(prik);

        action.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        action.setForeground(new java.awt.Color(51, 51, 255));
        action.setText("Pretraga");
        action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionActionPerformed(evt);
            }
        });

        action1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        action1.setForeground(new java.awt.Color(51, 51, 255));
        action1.setText("Obrisi text");
        action1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pretragaLayout = new javax.swing.GroupLayout(pretraga.getContentPane());
        pretraga.getContentPane().setLayout(pretragaLayout);
        pretragaLayout.setHorizontalGroup(
            pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pretragaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(im)
                .addGap(44, 44, 44)
                .addComponent(godin)
                .addGap(64, 64, 64)
                .addComponent(adr)
                .addGap(36, 36, 36)
                .addComponent(doh)
                .addGap(169, 169, 169))
            .addGroup(pretragaLayout.createSequentialGroup()
                .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pretragaLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pretragaLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pretragaLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pretragaLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pretragaLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dohoh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pretragaLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel21))
                    .addGroup(pretragaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pretragaLayout.createSequentialGroup()
                                .addComponent(action)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(action1))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pretragaLayout.setVerticalGroup(
            pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pretragaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(im)
                    .addComponent(godin)
                    .addComponent(adr)
                    .addComponent(doh))
                .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pretragaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pretragaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(dohoh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(action)
                    .addComponent(action1))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jRadioButton6.setText("jRadioButton6");

        jTextField10.setText("jTextField10");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Informacioni sistem Zaposlenih");

        jToggleButton1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(0, 51, 255));
        jToggleButton1.setText("Svi Zaposleni");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(0, 51, 255));
        jToggleButton2.setText("Izmjena Podataka");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(0, 51, 255));
        jToggleButton3.setText("Brisanje Uposlenika");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(0, 51, 255));
        jToggleButton4.setText("Novi Uposlenik");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zadatakhibernate/add_user_26px.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zadatakhibernate/group_26px.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zadatakhibernate/services_26px.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zadatakhibernate/t.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29))
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton4)
                    .addComponent(jLabel26))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jToggleButton1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jLabel28))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3)
                    .addComponent(jLabel29))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed

        unos.show();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        brisanje.show();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int opcija = JOptionPane.showOptionDialog(null, "Prikazi", "Prikaz zaposlenika", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sve zaposlenike", "Po kriterijumu"}, null);

        switch (opcija) {

            case JOptionPane.YES_OPTION:

                svi.show();

                break;

            case JOptionPane.NO_OPTION:

                pretraga.show();

                break;

        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        izmjena.show();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionActionPerformed

        
        boolean state = true;
        Thread t5 = new Thread() {

            @Override
            public void run() {

                if (state == true) {

        
        if (im.isSelected()) {
            String name = i.getText();

            String hql = "select zap from Person zap where zap.name = '" + name + "'";
            Query query = session.createQuery(hql);

            List<Person> zap = null;

            try {

                tx = session.beginTransaction();

                zap = query.list();

                tx.commit();

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }

            StringBuilder rezultat = new StringBuilder();

            for (Person person1 : zap) {
                rezultat.append(person1.getIdperson());
                rezultat.append("  ");
                rezultat.append(person1.getName());
                rezultat.append("  ");
                rezultat.append(person1.getAge());
                rezultat.append("  ");
                rezultat.append(person1.getAdress());
                rezultat.append("  ");
                rezultat.append(person1.getSalary());
                rezultat.append(" \n");

                prik.setText(rezultat.toString());

            }
        }

        if (godin.isSelected()) {
            String g1 = g.getText();
            int go = Integer.parseInt(g1);

            String hql1 = "select zap2 from Person zap2 where zap2.age = '" + go + "'";
            Query query1 = session.createQuery(hql1);

            List<Person> zap2 = null;

            try {

                tx = session.beginTransaction();

                zap2 = query1.list();

                tx.commit();

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }

            StringBuilder rezultat = new StringBuilder();

            for (Person person1 : zap2) {
                rezultat.append(person1.getIdperson());
                rezultat.append("  ");
                rezultat.append(person1.getName());
                rezultat.append("  ");
                rezultat.append(person1.getAge());
                rezultat.append("  ");
                rezultat.append(person1.getAdress());
                rezultat.append("  ");
                rezultat.append(person1.getSalary());
                rezultat.append(" \n");

                prik.setText(rezultat.toString());

            }
        }
        if (doh.isSelected()) {
            String g1 = dohoh.getText();
            int g2 = Integer.parseInt(g1);

            String hql1 = "select zap3 from Person zap3 where zap3.salary = '" + g2 + "'";
            Query query1 = session.createQuery(hql1);

            List<Person> zap4 = null;

            try {

                tx = session.beginTransaction();

                zap4 = query1.list();

                tx.commit();

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }

            StringBuilder rezultat = new StringBuilder();

            for (Person person1 : zap4) {
                rezultat.append(person1.getIdperson());
                rezultat.append("  ");
                rezultat.append(person1.getName());
                rezultat.append("  ");
                rezultat.append(person1.getAge());
                rezultat.append("  ");
                rezultat.append(person1.getAdress());
                rezultat.append("  ");
                rezultat.append(person1.getSalary());
                rezultat.append(" \n");

                prik.setText(rezultat.toString());

            }
        }
        if (adr.isSelected()) {
            String g1 = add.getText();

            String hql1 = "select zap3 from Person zap3 where zap3.adress = '" + g1 + "'";
            Query query1 = session.createQuery(hql1);

            List<Person> zap3 = null;

            try {

                tx = session.beginTransaction();

                zap3 = query1.list();

                tx.commit();

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }

            StringBuilder rezultat = new StringBuilder();

            for (Person person1 : zap3) {
                rezultat.append(person1.getIdperson());
                rezultat.append("  ");
                rezultat.append(person1.getName());
                rezultat.append("  ");
                rezultat.append(person1.getAge());
                rezultat.append("  ");
                rezultat.append(person1.getAdress());
                rezultat.append("  ");
                rezultat.append(person1.getSalary());
                rezultat.append(" \n");

                prik.setText(rezultat.toString());

            }

        }
                }
        
            }
        };
        t5.start();


    }//GEN-LAST:event_actionActionPerformed

    private void unesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unesiActionPerformed

        boolean state = true;

        Thread t = new Thread() {
            @Override
            public void run() {

                if (state == true) {

                    String z = ime.getText();
                    String x = godine.getText();
                    int x1 = Integer.parseInt(x);
                    String y = adresa.getText();
                    String q = dohodak.getText();
                    int q1 = Integer.parseInt(q);

                    p = new Person(z, x1, y, q1);
                    try {

                        tx = session.beginTransaction();

                        session.persist(p);

                        tx.commit();

                        JOptionPane.showMessageDialog(null, "Unos uspjesan!!!");

                    } catch (HibernateException e) {
                        if (tx != null) {
                            tx.rollback();
                        }
                        System.out.println(e);
                    }
                    finally{}
                    

                }

            }
;
        };
        t.start();


    }//GEN-LAST:event_unesiActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed

        String hql = "from Person zaposleni ";
        Query query = session.createQuery(hql);

        List<Person> zaposleni = null;

        try {

            tx = session.beginTransaction();

            zaposleni = query.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat = new StringBuilder();

        for (Person person1 : zaposleni) {

            rezultat.append(person1.getIdperson());
            rezultat.append("  ");
            rezultat.append(person1.getName());
            rezultat.append("  ");
            rezultat.append(person1.getAge());
            rezultat.append("  ");
            rezultat.append(person1.getAdress());
            rezultat.append("  ");
            rezultat.append(person1.getSalary());
            rezultat.append(" \n");

            sviz.setText(rezultat.toString());

        }


    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed

        if (ime1.isSelected()) {

            String id = izm.getText();
            int idd = Integer.parseInt(id);

            String nam = ime2.getText();

            String hql = "update Person zap set zap.name = '" + nam + "' " + " where zap.idperson = '" + idd + "'";
            Query query = session.createQuery(hql);

            List<Person> zap = null;

            try {

                tx = session.beginTransaction();

                query.executeUpdate();
                session.flush();
                session.clear();
                tx.commit();

                JOptionPane.showMessageDialog(null, "Izmjena uspjesno izvrsena.");

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }
        }
        if (godine1.isSelected()) {

            String id = izm.getText();
            int idd = Integer.parseInt(id);

            String nam = godine2.getText();

            String hql = "update Person zap set zap.age = '" + nam + "' " + " where zap.idperson = '" + idd + "'";
            Query query = session.createQuery(hql);

            List<Person> zap = null;

            try {

                tx = session.beginTransaction();

                query.executeUpdate();
                session.flush();
                session.clear();
                tx.commit();

                JOptionPane.showMessageDialog(null, "Izmjena uspjesno izvrsena.");

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }
        }
        if (adresa1.isSelected()) {

            String id = izm.getText();
            int idd = Integer.parseInt(id);

            String nam = adresa2.getText();

            String hql = "update Person zap set zap.adress = '" + nam + "' " + " where zap.idperson = '" + idd + "'";
            Query query = session.createQuery(hql);

            List<Person> zap = null;

            try {

                tx = session.beginTransaction();

                query.executeUpdate();
                session.flush();
                session.clear();
                tx.commit();

                JOptionPane.showMessageDialog(null, "Izmjena uspjesno izvrsena.");

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }
        }
        if (dohodak1.isSelected()) {

            String id = izm.getText();
            int idd = Integer.parseInt(id);

            String nam = doho2.getText();

            String hql = "update Person zap set zap.salary = '" + nam + "' " + " where zap.idperson = '" + idd + "'";
            Query query = session.createQuery(hql);

            List<Person> zap = null;

            try {

                tx = session.beginTransaction();

                query.executeUpdate();
                session.flush();
                session.clear();
                tx.commit();

                JOptionPane.showMessageDialog(null, "Izmjena uspjesno izvrsena.");

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                System.out.println(e);
            }
        }


    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed

        String del = d.getText();
        int dele = Integer.parseInt(del);
        String hql = "delete from Person zap where zap.idperson ='" + dele + "'";
        Query query = session.createQuery(hql);

        List<Person> zap = null;

        try {

            tx = session.beginTransaction();

            query.executeUpdate();

            tx.commit();

            JOptionPane.showMessageDialog(null, "Uspjesno obrisan zaposlenik.");

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }


    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void ime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ime1ActionPerformed
        godine1.setEnabled(false);
        adresa1.setEnabled(false);
        dohodak1.setEnabled(false);
        adresa2.setEnabled(false);
        godine2.setEnabled(false);

    }//GEN-LAST:event_ime1ActionPerformed

    private void godine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godine1ActionPerformed

        adresa1.setEnabled(false);
        dohodak1.setEnabled(false);
        doho2.setEnabled(false);
        ime1.setEnabled(false);
        ime2.setEnabled(false);
        adresa2.setEnabled(false);
    }//GEN-LAST:event_godine1ActionPerformed

    private void adresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresa1ActionPerformed
        ime1.setEnabled(false);
        godine1.setEnabled(false);
        dohodak1.setEnabled(false);
        ime2.setEnabled(false);
        godine2.setEnabled(false);
        doho2.setEnabled(false);
    }//GEN-LAST:event_adresa1ActionPerformed

    private void dohodak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dohodak1ActionPerformed
        ime1.setEnabled(false);
        godine1.setEnabled(false);
        adresa1.setEnabled(false);
        ime2.setEnabled(false);
        godine2.setEnabled(false);
        adresa2.setEnabled(false);
    }//GEN-LAST:event_dohodak1ActionPerformed

    private void imActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imActionPerformed
        godin.setEnabled(false);
        adr.setEnabled(false);
        doh.setEnabled(false);
        add.setEnabled(false);
        dohoh.setEnabled(false);
        g.setEnabled(false);
    }//GEN-LAST:event_imActionPerformed

    private void godinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godinActionPerformed
        im.setEnabled(false);
        adr.setEnabled(false);
        doh.setEnabled(false);
        i.setEnabled(false);
        add.setEnabled(false);
        dohoh.setEnabled(false);
    }//GEN-LAST:event_godinActionPerformed

    private void adrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrActionPerformed
        im.setEnabled(false);
        godin.setEnabled(false);
        doh.setEnabled(false);
        i.setEnabled(false);
        g.setEnabled(false);
        dohoh.setEnabled(false);
    }//GEN-LAST:event_adrActionPerformed

    private void dohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dohActionPerformed
        im.setEnabled(false);
        godin.setEnabled(false);
        adr.setEnabled(false);
        i.setEnabled(false);
        g.setEnabled(false);
        add.setEnabled(false);
    }//GEN-LAST:event_dohActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String t = izm.getText();
        int t1 = Integer.parseInt(t);

        String hql1 = "select zap3 from Person zap3 where zap3.idperson= '" + t1 + "'";
        Query query1 = session.createQuery(hql1);

        List<Person> zap3 = null;

        try {

            tx = session.beginTransaction();

            zap3 = query1.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat = new StringBuilder();

        for (Person person1 : zap3) {
            rezultat.append(person1.getIdperson());
            rezultat.append("  ");
            rezultat.append(person1.getName());
            rezultat.append("  ");
            rezultat.append(person1.getAge());
            rezultat.append("  ");
            rezultat.append(person1.getAdress());
            rezultat.append("  ");
            rezultat.append(person1.getSalary());
            rezultat.append(" \n");

            pr.setText(rezultat.toString());

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
       d.setText("");
       br.setText("");
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        izm.setText("");
        ime2.setText("");
        adresa2.setText("");
        godine2.setText("");
        doho2.setText("");
        ime1.setSelected(false);
        godine1.setSelected(false);
        adresa1.setSelected(false);
        dohodak1.setSelected(false);
        izm.setEnabled(true);
        ime2.setEnabled(true);
        adresa2.setEnabled(true);
        godine2.setEnabled(true);
        doho2.setEnabled(true);
        ime1.setEnabled(true);
        godine1.setEnabled(true);
        adresa1.setEnabled(true);
        dohodak1.setEnabled(true);
        pr.setText(" ");
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void action1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action1ActionPerformed
        prik.setText(" ");
        i.setText("");
        g.setText("");
        add.setText("");
        dohoh.setText("");
        im.setSelected(false);
        godin.setSelected(false);
        adr.setSelected(false);
        doh.setSelected(false);
        i.setEnabled(true);
        g.setEnabled(true);
        add.setEnabled(true);
        dohoh.setEnabled(true);
        im.setEnabled(true);
        godin.setEnabled(true);
        adr.setEnabled(true);
        doh.setEnabled(true);
    }//GEN-LAST:event_action1ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        String hql = "from Person zaposleni ";
        Query query = session.createQuery(hql);

        List<Person> zaposleni = null;

        try {

            tx = session.beginTransaction();

            zaposleni = query.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat = new StringBuilder();

        for (Person person1 : zaposleni) {

            rezultat.append(person1.getIdperson());
            rezultat.append("  ");
            rezultat.append(person1.getName());
            rezultat.append("  ");
            rezultat.append(person1.getAge());
            rezultat.append("  ");
            rezultat.append(person1.getAdress());
            rezultat.append("  ");
            rezultat.append(person1.getSalary());
            rezultat.append(" \n");

            br.setText(rezultat.toString());

        }

    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void unesi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unesi1ActionPerformed
       ime.setText("");
       godine.setText("");
       adresa.setText("");
       dohodak.setText("");
    }//GEN-LAST:event_unesi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Glavni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton action;
    private javax.swing.JToggleButton action1;
    private javax.swing.JTextField add;
    private javax.swing.JRadioButton adr;
    private javax.swing.JTextField adresa;
    private javax.swing.JRadioButton adresa1;
    private javax.swing.JTextField adresa2;
    private javax.swing.JTextArea br;
    private javax.swing.JFrame brisanje;
    private javax.swing.JTextField d;
    private javax.swing.JRadioButton doh;
    private javax.swing.JTextField doho2;
    private javax.swing.JTextField dohodak;
    private javax.swing.JRadioButton dohodak1;
    private javax.swing.JTextField dohoh;
    private javax.swing.JTextField g;
    private javax.swing.JRadioButton godin;
    private javax.swing.JTextField godine;
    private javax.swing.JRadioButton godine1;
    private javax.swing.JTextField godine2;
    private javax.swing.JTextField i;
    private javax.swing.JRadioButton im;
    private javax.swing.JTextField ime;
    private javax.swing.JRadioButton ime1;
    private javax.swing.JTextField ime2;
    private javax.swing.JTextField izm;
    private javax.swing.JFrame izmjena;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JTextArea pr;
    private javax.swing.JFrame pretraga;
    private javax.swing.JTextArea prik;
    private javax.swing.JFrame svi;
    private javax.swing.JTextArea sviz;
    private javax.swing.JToggleButton unesi;
    private javax.swing.JToggleButton unesi1;
    private javax.swing.JFrame unos;
    // End of variables declaration//GEN-END:variables
}
