package zadatakhibernate;
// Generated May 6, 2019 10:25:45 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="hibernate"
)
public class Person  implements java.io.Serializable {


     private Integer idperson;
     private String name;
     private int age;
     private String adress;
     private int salary;

    public Person() {
    }

    public Person(String name, int age, String adress, int salary) {
       this.name = name;
       this.age = age;
       this.adress = adress;
       this.salary = salary;
     
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idperson", unique=true, nullable=false)
    public Integer getIdperson() {
        return this.idperson;
    }
    
    public void setIdperson(Integer idperson) {
        this.idperson = idperson;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="age", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="adress", nullable=false, length=45)
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }

    
    @Column(name="salary", nullable=false)
    public int getSalary() {
        return this.salary;
    }
    
    public void setSalary(int salary) {
        this.salary = salary;
    }

public String toString(){

return idperson+ name + age + adress + salary;

}


}


